### ISSUE TITLE
Firefox + Safari 5.1: cover images/videos improper widht/height

### ISSUE THREAD

**Issue by ronxjansen** [flipbase/www#11]
<img width="1440" alt="screen shot 2017-06-14 at 13 27 42" src="https://user-images.githubusercontent.com/461952/27130140-49054bcc-5105-11e7-8135-944053250f9b.png">

**Comment by ronxjansen** [comment]
Related to #5

**Comment by ronxjansen** [comment]
Issue also occurs on Safari 5.1, Firefox 48-53 (lower then 47 we didn't test) on Win7-Win10 and iOS Sierra. So basically: all Firefox browser have this issue.

**Comment by SZharkov** [comment]
Fixed for Firefox and iOS Sierra., but I didn't find a solution for windows Safari 5.1, I even can't see console.log commands in this version. If this is principle, I could do deep research to resolve the issue for Safari 5.1 as well. Just let me know.

**Comment by ronxjansen** [comment]
I verified that on Safari 10.1 (iOS Sierra) and Safari 8 (iOS Yosemite) this issue is fixed. However, this issue still occurs on Windows 8 and iOS Sierra Firefox 54.0. Since Firefox has a relative large market share, this issue has priority. 

<img width="1440" alt="screen shot 2017-06-21 at 10 56 14" src="https://user-images.githubusercontent.com/461952/27375689-4336cf52-5670-11e7-8cc4-5e0532d5119e.png">

<img width="1440" alt="screen shot 2017-06-21 at 10 55 42" src="https://user-images.githubusercontent.com/461952/27375658-2f7cd178-5670-11e7-80f1-c6994a25b37c.png">
