### ISSUE TITLE
IE9: play button not shown in the middle of the video element on the /jobs page 

### ISSUE THREAD

**Issue by ronxjansen** [flipbase/www#8]
<img width="1440" alt="screen shot 2017-06-14 at 13 17 47" src="https://user-images.githubusercontent.com/461952/27129805-e55078dc-5103-11e7-9d72-642cc14679ce.png">

**Comment by ronxjansen** [comment]
On mobile devices the button is also not shown in the middle (this is Samsung S5):

<img width="1440" alt="screen shot 2017-06-14 at 13 43 18" src="https://user-images.githubusercontent.com/461952/27130647-7446667a-5107-11e7-8f83-758d1e57c749.png">

**Comment by SZharkov** [comment]
Fixed

**Comment by ronxjansen** [comment]
I've pulled your changes; build the new assets, but unfortunately  this issue is not fixed when testing it on IE9:

<img width="1440" alt="screen shot 2017-06-21 at 10 37 57" src="https://user-images.githubusercontent.com/461952/27374946-f13ebd56-566d-11e7-8099-acf28d611753.png">

**Comment by SZharkov** [comment]
Check the new commit
